apiVersion: compute.yextly.io/v1alpha1
kind: WorkerTemplate
metadata:
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/managed-by: kustomize
  name: workertemplate-sample
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: worker
              image: busybox
              command: ["/bin/sh", "-c", "ls /var/secrets/secret1"]
              volumeMounts:
                - name: volume1
                  mountPath: /var/secrets/secret1
                  readOnly: true
          volumes:
            - name: volume1
              secret:
                secretName: secret1
